name: CI/CD Pipeline for API Gateway
on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and run tests
        run: mvn clean verify

      - name: Show target directory
        run: ls -la target || echo "target not found"

      - name: Build Docker image
        run: docker build -t api-gateway:${{ github.sha }} .

